[server]
enableStaticServing = true

[theme]
primaryColor = "#0055A2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f2f2f2"
textColor = "#000000"
font = "sans serif"

[theme.navbar]
backgroundColor = "#0055A2"
color = "#FFFFFF"

[theme.sidebar]
backgroundColor = "#E5A823"
color = "#000000"

[theme.button]
primaryColor = "#0055A2"
secondaryColor = "#E5A823"
textColor = "#FFFFFF"
